/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchAssistantRouteImport } from './routes/research-assistant'
import { Route as ProgressTrackerRouteImport } from './routes/progress-tracker'
import { Route as EmailAssistantRouteImport } from './routes/email-assistant'
import { Route as DailyReportRouteImport } from './routes/daily-report'
import { Route as AiToolFinderRouteImport } from './routes/ai-tool-finder'
import { Route as IndexRouteImport } from './routes/index'

const ResearchAssistantRoute = ResearchAssistantRouteImport.update({
  id: '/research-assistant',
  path: '/research-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressTrackerRoute = ProgressTrackerRouteImport.update({
  id: '/progress-tracker',
  path: '/progress-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailAssistantRoute = EmailAssistantRouteImport.update({
  id: '/email-assistant',
  path: '/email-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyReportRoute = DailyReportRouteImport.update({
  id: '/daily-report',
  path: '/daily-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolFinderRoute = AiToolFinderRouteImport.update({
  id: '/ai-tool-finder',
  path: '/ai-tool-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-tool-finder': typeof AiToolFinderRoute
  '/daily-report': typeof DailyReportRoute
  '/email-assistant': typeof EmailAssistantRoute
  '/progress-tracker': typeof ProgressTrackerRoute
  '/research-assistant': typeof ResearchAssistantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-tool-finder': typeof AiToolFinderRoute
  '/daily-report': typeof DailyReportRoute
  '/email-assistant': typeof EmailAssistantRoute
  '/progress-tracker': typeof ProgressTrackerRoute
  '/research-assistant': typeof ResearchAssistantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-tool-finder': typeof AiToolFinderRoute
  '/daily-report': typeof DailyReportRoute
  '/email-assistant': typeof EmailAssistantRoute
  '/progress-tracker': typeof ProgressTrackerRoute
  '/research-assistant': typeof ResearchAssistantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-tool-finder'
    | '/daily-report'
    | '/email-assistant'
    | '/progress-tracker'
    | '/research-assistant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-tool-finder'
    | '/daily-report'
    | '/email-assistant'
    | '/progress-tracker'
    | '/research-assistant'
  id:
    | '__root__'
    | '/'
    | '/ai-tool-finder'
    | '/daily-report'
    | '/email-assistant'
    | '/progress-tracker'
    | '/research-assistant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiToolFinderRoute: typeof AiToolFinderRoute
  DailyReportRoute: typeof DailyReportRoute
  EmailAssistantRoute: typeof EmailAssistantRoute
  ProgressTrackerRoute: typeof ProgressTrackerRoute
  ResearchAssistantRoute: typeof ResearchAssistantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research-assistant': {
      id: '/research-assistant'
      path: '/research-assistant'
      fullPath: '/research-assistant'
      preLoaderRoute: typeof ResearchAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress-tracker': {
      id: '/progress-tracker'
      path: '/progress-tracker'
      fullPath: '/progress-tracker'
      preLoaderRoute: typeof ProgressTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-assistant': {
      id: '/email-assistant'
      path: '/email-assistant'
      fullPath: '/email-assistant'
      preLoaderRoute: typeof EmailAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-report': {
      id: '/daily-report'
      path: '/daily-report'
      fullPath: '/daily-report'
      preLoaderRoute: typeof DailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tool-finder': {
      id: '/ai-tool-finder'
      path: '/ai-tool-finder'
      fullPath: '/ai-tool-finder'
      preLoaderRoute: typeof AiToolFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiToolFinderRoute: AiToolFinderRoute,
  DailyReportRoute: DailyReportRoute,
  EmailAssistantRoute: EmailAssistantRoute,
  ProgressTrackerRoute: ProgressTrackerRoute,
  ResearchAssistantRoute: ResearchAssistantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
